config/routes.rb
Rails.application.routes.draw do
  
  resources :articles
  root to: 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true
	validates :author, presence: true
	validates :post, presence: true
	validates :title, uniqueness: true	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
	
	def index
		@articles = Article.all
	end

	def show
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
        redirect_to @article, notice: 'Article was successfully created.'

	end

	def edit
	end

	def update
		Article.find(params[:id]).update(article_params)
		redirect_to @article, notice: 'Article was successfully updated.'

	end

	def destroy
		Article.find(params[:id]).destroy
 		redirect_to articles_url, notice: 'Article was successfully destroyed.'

	end

	#Prevent the reception of dangerous params
	private
	def article_params
      params.require(:article).permit(:title, :author, :date, :published, :post)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	def index
		@articles = Article.all
		@article = Article.new
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.create(article_params)
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@articles = Article.all
		@article = Article.find(params[:id])
		@article.update(article_params)
	end

	def destroy
		Article.find(params[:id]).destroy
	end

	#Prevent the reception of dangerous params
	private
	def article_params
      params.require(:article).permit(:title, :author, :date, :published, :post)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/article/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Date:</strong>
  <%= @article.date %>
</p>

<p>
  <strong>Published:</strong>
  <%= @article.published %>
</p>

<p>
  <strong>Post:</strong>
  <%= @article.post %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/_article_index.html.erb
<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.author %></td>
    <td class="text-center"><%= article.date %></td>

    <% if article.published %>
      <td class="text-center success">YES</td>
    <% else %>
      <td class="text-center danger">NO</td>
    <% end %>
    
    
    <td><%= article.post %></td>
    <td class="text-center"><%= link_to 'Show', article, :class => "button btn btn-primary", remote: true
     %></td>
    <td class="text-center"><%= link_to 'Edit', edit_article_path(article), :class => "button btn btn-warning", remote: true %></td>
    <td class="text-center"><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button btn btn-danger" %></td>
  </tr>
<% end %>

app/views/articles/_article_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">New Article</h4>
      </div>
      <div class="modal-body">
		    <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/_article_modal_edit.html.erb
<div class="modal fade" id="myModalEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Article</h4>
      </div>
      <div class="modal-body">
		    <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/_article_modal_show.html.erb
<div class="modal fade" id="myModalEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Article</h4>
      </div>
      <div class="modal-body">
        <p>
          <strong>Title:</strong>
          <%= @article.title %>
        </p>

        <p>
          <strong>Author:</strong>
          <%= @article.author %>
        </p>

        <p>
          <strong>Date:</strong>
          <%= @article.date %>
        </p>

        <p>
          <strong>Published:</strong>
          <%= @article.published %>
        </p>

        <p>
          <strong>Post:</strong>
          <%= @article.post %>
        </p>
        <%= link_to 'Edit', edit_article_path(@article), :class => "button btn btn-warning", remote: true %>
        <%= link_to 'Back', articles_path, :class => "button btn btn-info" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<form role="form">
  <%= form_for(@article, remote: true) do |f| %>
    <div class="field form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :author %><br>
      <%= f.text_field :author, :class => "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :date %><br>
      <%= f.date_select :date, :class => "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.check_box :published %>
      <%= f.label :published %>
    </div>
    <div class="field form-group">
      <%= f.label :post %> 
      <%= f.text_area :post, :class => "form-control" %>
    </div>
    <div class="actions form-group">
      <%= f.submit 'Upload Article', :class => 'btn btn-success' %>
    </div>
  <% end %>
</form>

app/views/articles/create.js.erb
// Este archivo se usa para guardar los datos dentro del formulario creando el nuevo objeto, esconder el modal y actualizar la tabla
<% if @article.errors.any? %>
	$('.alert-danger').remove();
    <% @article.errors.full_messages.each do |message| %>
    	$('.modal-body').prepend('<div class="alert alert-danger"><%= message %></div>');
    <% end %>
<% else %>
	$('#myModal').modal('hide');
	$('#articles_table').append('<tr> \
	<td><%= @article.title %></td> \
	<td><%= @article.author %></td> \
	<td class="text-center"><%= @article.date %></td> \
	<% if @article.published %> \
    	<td class="text-center success">YES</td> \
    <% else %> \
    	<td class="text-center danger">NO</td>  \
    <% end %> \
	<td><%= @article.post %></td> \
	<td class="text-center"><%= link_to "Show", @article, :class => "button btn btn-primary" %></td> \
	<td class="text-center"><%= link_to "Edit", edit_article_path(@article), :class => "button btn btn-warning", remote: true %></td> \
	<td class="text-center"><%= link_to "Destroy", @article, method: :delete, data: { confirm: "Are you sure?" }, :class => "button btn btn-danger" %></td> \
	</tr>');
<% end %>

app/views/articles/edit.js.erb
$('<%= j render "article_modal_edit" %>').modal();

app/views/articles/index.html.erb
<h1 class="text-center">Listing articles</h1>

<table class="table table-bordered table-hover table-condensed" id="articles_table">
  <thead>
    <tr class="active">
      <th>Title</th>
      <th>Author</th>
      <th class="text-center">Date</th>
      <th class="text-center">Published</th>
      <th>Post</th>
      <th class="text-center" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render "article_index" %>
  </tbody>
</table>

<%= link_to 'New Article' , new_article_path, :class => "button btn btn-lg btn-success", remote: true %>

app/views/articles/new.js.erb
// Este archivo se usa para mostrar el formulario para crear un nuevo elemento
$('<%= j render "article_modal" %>').modal();

app/views/articles/show.js.erb
// Este archivo se usa para mostrar la informacion almacenada en el articulo
$('<%= j render "article_modal_show" %>').modal();

app/views/articles/update.js.erb
<% if @article.errors.any? %>
	$('.alert-danger').remove();
    <% @article.errors.full_messages.each do |message| %>
    	$('.modal-body').prepend('<div class="alert alert-danger"><%= message %></div>');
    <% end %>
<% else %>
	$('#myModalEdit').modal('hide').remove();
	$('#articles_table tbody').html('').append('<%= j render "article_index" %>');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArticlesMakeItRealManualBootstrap</title>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= yield %>
</div>
</body>
</html>